### ISSUE TITLE
ChanServ/SUSPEND lacks checks to prevent people from suspending their own access

### ISSUE THREAD

**Issue by GLolol** [XthemeOrg/Xtheme#49]

**Comment by siniStar7boy** [comment]
As mentioned on IRC, this feature is still in _alpha_ stages.  A check will be added to ensure that "_silly_" users are not able to suspend themselves.

**Comment by GLolol** [comment]
Why not leave the issue open then so people can see it?

**Comment by siniStar7boy** [comment]
Since Founders cannot suspend themselves, and others have brought the suggestion that a user may want to "take a break from their privileges", I am closing this issue as it is post-Xtheme and not considered an issue anymore.  Founders (should they somehow manage to get suspended, somehow) can delete their suspensions.
