### ISSUE TITLE
8.0.0-dev2 Bugs

### ISSUE THREAD

**Issue by mohdschizo** [XthemeOrg/Xtheme#78]
Found a few bug(s) in NickServ - Xtheme 8.0.0-dev2 version:

- AJOIN add #channel 
- set ENFORCE/ENFORCETIME time

Services will quit after issuing the command

**Comment by siniStar7boy** [comment]
@mohdschizo I could not replicate the issue with `NickServ SET ENFORCE` or `NickServ SET ENFORCETIME`, however, thank you for reporting the issue with `AJOIN`.  

I will see if the issue with `NickServ SET ENFORCE/ENFORCETIME` can be replicated on an additional test machine; but will otherwise need a backtrace.
